### PR TITLE
support alternative template file encodings

### LINKED ISSUE #178: Whiskers doesn't read frontmatter in files encoded as UTF-8 with BOM
Only noticed this because one of the files I was working with was already encoded as UTF-8 with BOM for some reason, and was giving errors about variables that I defined in the frontmatter not being found.

eg

```tera
---
whiskers:
  version: 2.0.2
accent: "mauve"
---

accent: {{ accent }}
```

encoded as UTF-8 with BOM gives the output

```
Warning: No Whiskers version requirement specified in template.
This template may not be compatible with this version of Whiskers.

To fix this, add the minimum supported Whiskers version to the template frontmatter as follows:

---
whiskers:
    version: "2.0.2"
---

Error: Single-output render failed

Caused by:
    0: Template render failed
    1: Failed to render 'test.tera'
    2: Variable `accent` not found in context while rendering 'test.tera'
```

This really isn't a big deal, I've already easily re-encoded the files as just UTF-8, but it'd be nice if whiskers either gave a more useful error message, or read the frontmatter, in this case

### PR DESCRIPTION
**Pull request by backwardspy**
currently supports whatever encodings the [encoding_rs_io crate](https://github.com/BurntSushi/encoding_rs_io) supports

there are test cases for UTF-8, UTF-8 with BOM, UTF-16 LE, and UTF-16 BE.

resolves #178

### CODE REVIEW

**Comment by nekowinston** [comment]
Did you consider an alternative of keeping the target file encoding in the whiskers metadata?
From my own experience where encoding mattered (Hearts of Iron IV modding, lol), keeping track of the correct encoding can be a tad annoying.
e.g.

```yaml
whiskers:
  encoding: utf8-bom
  version: "2.1.0"
```

instead of requiring the input to have the same encoding as the output.

**Comment by backwardspy** [comment]
> ```yaml
> whiskers:
>   encoding: utf8-bom
>   version: "2.1.0"
> ```

i hadn't considered that, but i like the idea! i think i'll tackle encoding in another PR as the choice of crates for this stuff seems to be split around decoding & encoding. i imagine i'll need to bring in another dependency for it.

> instead of requiring the input to have the same encoding as the output.

right now we only care about encoding on input, all outputs are utf-8 per rust's defaults. those utf-16 files in the diff are fixtures for tests that ensure we can read & render those files correctly.

**Comment by nekowinston** [comment]
> right now we only care about encoding on input, all outputs are utf-8 per rust's defaults. those utf-16 files in the diff are fixtures for tests that ensure we can read & render those files correctly.

oh I misunderstood this PR, I guess this would've been a better comment to make in #178 🙃 
seems fair to split it in two PRs then 👍

**Comment by backwardspy** [comment]
to be fair, i did imply on that issue that i could carry the encoding through to writing the file too. i much prefer your solution.

**Pull request merged**
