### PR TITLE
docs(whiskers): fix source install command

### PR DESCRIPTION
**Pull request by backwardspy**

### CODE REVIEW

**Comment by uncenter** [comment]
This change should also be applied to https://github.com/catppuccin/toolbox/blob/main/catwalk/README.md I think?

**Comment by backwardspy** [comment]
> This fix should also be applied to [`main`/catwalk/README.md](https://github.com/catppuccin/toolbox/blob/main/catwalk/README.md?rgh-link-date=2024-03-05T20%3A17%3A29Z) I think?

looks like it yep, fixed in #142

**Comment by uncenter** [comment]
I dunno if that has to be a separate PR but yeah lol great

**Review by sgoudham — APPROVED** [review]
Even nicer catch!

**Pull request merged**
