### PR TITLE
feat!: Catwalk Rust Rewrite

### PR DESCRIPTION
**Pull request by DakshG07**
_Unsatisfied with his own creation, he turned to the crab sitting beside his shoulder. "Shall we?" he asked. "We shall"._
A rewrite of `catwalk`, now in Rust. Very WIP.

# Roadmap
- [x] Layouts
  - [x] Composite
  - [x] Grid
  - [x] Stacked
- [x] ~~Custom Margins~~
- [x] ~~Custom Background~~
- [x] ~~Rainbow Background~~
- [x] ~~Custom Border Radius~~
  - [x] ~~Inner~~
  - [x] ~~Outer~~
- [x] ~~Shadows~~
- [x] WebP Export support (Rust specific)
- [x] Show help screen when no arguments are provided (Rust specific)
- [x] Update documentation

# Benefits
The benefits of Rust are obvious: speed. The Rust version of `catwalk` is 16x times faster than the Python version. (This was tested by running both the Python version and Rust version with no extra settings, on the screenshots from the VSCode repo. The Python version took 7182ms and the Rust version took 428ms. Times were measured in Powershell using the `Measure-Command` command.)

In addition, the Rust version implements basic parallelism to speed up the operations even more (using the incredible `rayon` library, this was more than trivial). This allows it to calculate the masks for the screenshots simultaneously (the masks can be calculated individually of one another).

I also took this opportunity to redo any things I didn't quite like (for example, the calculations for the actual slant masks in the code were EXTREMELY verbose, however the newer Rust version is much more idiomatic).

# Drawbacks
One obvious drawback of Rust is a slightly larger codebase. Rust is fundamentally more verbose than Python, and the code shows it.

We would also have rewrite all the Python versions' features (there are quite a few). I've been wanting to rewrite `catwalk` for a while, and thought now would be a good time, seeing as it hasn't been updated in close to a year. This PR implements the original base feature (the result you get from running the command with just the file names), and definitely has a long ways to go.

Lastly, the Rust `image` library is much more barebones than the `Pillow`. A good example would be my custom masking implementation in `mask.rs`, where I have to implement basic masking myself (it's not "real" masking; however this extremely niche implementation is all that's required for our use case). So certain features may require a bit of work (the `image` library does provide `imageops`, which contains some useful functions for us, but it's extremely barebones compared to the `Pillow` library).

Goal is to achieve feature parity with the Python version. The same command run on the Python version and the Rust version should create extremely similar, if not exactly the same, output. 

That's all I really have to say about this. Thoughts?

### CODE REVIEW

**Comment by DakshG07** [comment]
If anyone has any complaints/ideas for things to add to `catwalk`, feel free to suggest them.

**Comment by DakshG07** [comment]
I've significantly reduced the feature set as per some discussion on Discord, which pretty much makes it finished.

**Comment by DakshG07** [comment]
The last thing to do would be install instructions, but I think we'd want to upload this to Cargo under the organization account, right?

**Comment by DakshG07** [comment]
The install instructions reference a `catppuccin-catwalk` Cargo package, but I'm pretty sure we'd want to put that package under the org's account.

**Comment by DakshG07** [comment]
I also have no more features to really add, so I'll have this ready for review.

**Comment by nekowinston** [comment]
I'll have a final look over the Nix stuff tomorrow, then I'll go ahead and merge this.
I'd also love to have WASM bindings for an online version.
Thanks for your work rewriting this in Rust.

**Comment by nekowinston** [comment]
Took a while longer to fix some issues, here are new benchmarks:

Benchmark 1 is ffe422d5ec19819318b95f199660719c3a9bdedd
Benchmark 2 is 0ae2659d92bcfd4b0769b1244936e694f944d0d5
Benchmark 3 is currently released python3-catwalk
```
Benchmark 1: ./catwalk-rust-v1 ./latte.webp frappe.webp macchiato.webp mocha.webp
  Time (mean ± σ):     471.4 ms ±   4.3 ms    [User: 440.7 ms, System: 58.0 ms]
  Range (min … max):   468.1 ms … 479.6 ms    10 runs

Benchmark 2: ./catwalk-rust-aa latte.webp frappe.webp macchiato.webp mocha.webp
  Time (mean ± σ):      3.774 s ±  0.031 s    [User: 3.261 s, System: 0.512 s]
  Range (min … max):    3.736 s …  3.836 s    10 runs

Benchmark 3: catwalk latte.webp frappe.webp macchiato.webp mocha.webp
  Time (mean ± σ):      4.158 s ±  0.033 s    [User: 3.755 s, System: 0.402 s]
  Range (min … max):    4.129 s …  4.225 s    10 runs
  ```

The initial implementation in this PR was so fast because Anti-Aliasing and lossless WebP export weren't implemented yet, those are done now.

- The `image` dependency changed to `ril`, since it offers better paste functions.
- shell completion that's included at build time
- WASM support has been added

**Review by nekowinston — APPROVED** [review]

**Review by nekowinston — CHANGES_REQUESTED** [review]
Ok actually layout grid still isn't implemented correctly

**Review by nekowinston — APPROVED** [review]
Third time's the charm

**Pull request merged**
