### PR TITLE
feat: implement hex formatting support

### LINKED ISSUE #164: add hex formatting options to frontmatter
it'd be nice to be able to configure how whiskers represents colour as hexadecimal.

for example, this template:

```yaml
---
whiskers:
  hex:
    capitalize: true
    prefix: "#"
---
{red.hex}
```

would produce `#D20F39` instead of the default `d20f39`.

`capitalize` + `prefix` as options gives us a good amount of flexibility out of the box for common formats like `#RRGGBB` and `0xRRGGBB`, but it's worth considering a more complex implementation that could allow more control, for example being able to specify a format string like `0xFF{b:02X}{g:02X}{b:02X}` to produce `0xFFBBGGRR` format colours.

### PR DESCRIPTION
**Pull request by rubyowo**
Closes catppuccin/whiskers#8

I'd like to refactor this in the future or sometime else, it's a bit ugly currently.

### CODE REVIEW

**Comment by backwardspy** [comment]
just dropping an update on this; i've not forgotten about it but i haven't had the time so far to give it the review it deserves. i should be able to work on it in the coming days.

**Comment by sgoudham** [comment]
Caught up with @backwardspy on discord, he still plans on coming back to this and would like to have an input in it :+1:

**Comment by nullishamy** [comment]
Speaking broadly, I'm not super into having loads of extra parameters everywhere. Can we somehow centralise this? Also not a fan of the `String` type being used here, I think at least a type alias to describe what the format represents would be a good improvement at, perhaps a struct that can handle the rendering too, let's see.

**Comment by sgoudham** [comment]
The code has moved to https://github.com/catppuccin/whiskers so I'll be closing this PR. I know @backwardspy is currently improving/iterating on the idea here and will most likely raise another PR himself.

**Comment by backwardspy** [comment]
yes indeed! thanks so much for your work on this @rubyowo; i'm building on top of it and you will be co-author of the new commits.

**Pull request closed without merging**
